import {Roboto} from  'next/font/google'
import { Open_Sans } from 'next/font/google';


import "./globals.scss";

const roboto = Roboto({
  subsets: ['cyrillic'],
  variable: "--font-roboto",
  weight: ['400', '500','700', '900'],
});


const openSans = Open_Sans({
  subsets: ['cyrillic'],
  variable: "--font-open-sans",
  weight: ['400', '500', '600', '700', '800'],
});


// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Intele Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
